package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"archive/zip"
	"coderefinery/graph/model"
	"coderefinery/internal/core/domain"
	"coderefinery/internal/infrastructure/middleware"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

// CreateRepository is the resolver for the createRepository field.
func (r *mutationResolver) CreateRepository(ctx context.Context, name string, path string) (*model.Repository, error) {
	repo, err := r.RepoService.Create(ctx, name, path, false)
	if err != nil {
		return nil, err
	}
	return mapDomainRepoToModel(repo), nil
}

// ReindexRepository is the resolver for the reindexRepository field.
func (r *mutationResolver) ReindexRepository(ctx context.Context, id string) (bool, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid uuid: %w", err)
	}

	if err := r.RepoService.Reindex(ctx, uid); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteRepository is the resolver for the deleteRepository field.
func (r *mutationResolver) DeleteRepository(ctx context.Context, id string) (bool, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid uuid: %w", err)
	}

	if err := r.RepoService.Delete(ctx, uid); err != nil {
		return false, err
	}
	return true, nil
}

// UploadRepository is the resolver for the uploadRepository field.
func (r *mutationResolver) UploadRepository(ctx context.Context, name string, file graphql.Upload) (*model.Repository, error) {
	// 1. Validierung
	if !strings.HasSuffix(strings.ToLower(file.Filename), ".zip") {
		return nil, fmt.Errorf("only .zip files are allowed")
	}

	// 2. Zielpfad vorbereiten (nutzt Config für UploadDir)
	projectID := uuid.New()
	uploadDir := r.Config.Storage.UploadDir // Stelle sicher, dass r.Config verfügbar ist (siehe Schritt 4)
	targetDir := filepath.Join(uploadDir, projectID.String())

	// Verzeichnis erstellen
	if err := os.MkdirAll(targetDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create target directory: %w", err)
	}

	// 3. Entpacken (Logik adaptiert aus upload.go)
	if err := unzipFile(file.File, file.Size, targetDir); err != nil {
		os.RemoveAll(targetDir) // Aufräumen bei Fehler
		return nil, fmt.Errorf("failed to unzip: %w", err)
	}

	// 4. Repo erstellen (via RepoService)
	// Wir setzen isManaged=true, da wir die Dateien verwalten
	repo, err := r.RepoService.Create(ctx, name, targetDir, true)
	if err != nil {
		os.RemoveAll(targetDir)
		return nil, err
	}

	return mapDomainRepoToModel(repo), nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	// 1. User anlegen
	_, err := r.AuthService.Register(ctx, username, password)
	if err != nil {
		return nil, err
	}

	// 2. Direkt einloggen (Token & User holen)
	token, user, err := r.AuthService.Login(ctx, username, password)
	if err != nil {
		return nil, fmt.Errorf("login after registration failed: %w", err)
	}

	return &model.AuthPayload{
		Token: token,
		User:  mapDomainUserToModel(user),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.AuthPayload, error) {
	// Nutzt jetzt die neue Signatur (token, user, error)
	token, user, err := r.AuthService.Login(ctx, username, password)
	if err != nil {
		return nil, errors.New("invalid credentials")
	}

	return &model.AuthPayload{
		Token: token,
		User:  mapDomainUserToModel(user),
	}, nil
}

// SetEmbeddingModel is the resolver for the setEmbeddingModel field.
func (r *mutationResolver) SetEmbeddingModel(ctx context.Context, model string) (bool, error) {
	// 1. Check if model exists/is available
	available, err := r.Embedder.ListModels(ctx)
	if err != nil {
		return false, fmt.Errorf("failed to list models: %w", err)
	}

	found := false
	for _, m := range available {
		if m == model {
			found = true
			break
		}
	}
	if !found {
		return false, fmt.Errorf("model %s not available", model)
	}

	// 2. Check if model actually changed
	if r.Embedder.GetCurrentModel() == model {
		return true, nil // No change needed
	}

	// 3. Set new model
	if err := r.Embedder.SetModel(model); err != nil {
		return false, err
	}

	// 4. Delete ALL indices (vectors are now incompatible)
	if err := r.RepoService.DeleteAllIndices(ctx); err != nil {
		return false, fmt.Errorf("failed to clear indices: %w", err)
	}

	// 5. Update config
	r.Config.LLM.EmbeddingModel = model

	// 6. Trigger reindex of all repositories
	repos, err := r.RepoService.List(ctx)
	if err != nil {
		return false, err
	}

	for _, repo := range repos {
		// KORREKTUR: repo.ID ist bereits eine UUID, kein Parse nötig!
		go func(id uuid.UUID) {
			_ = r.RepoService.Reindex(context.Background(), id)
		}(repo.ID)
	}

	return true, nil
}

// Repositories is the resolver for the repositories field.
func (r *queryResolver) Repositories(ctx context.Context) ([]*model.Repository, error) {
	repos, err := r.RepoService.List(ctx)
	if err != nil {
		return nil, err
	}

	var result []*model.Repository
	for _, repo := range repos {
		result = append(result, mapDomainRepoToModel(repo))
	}
	return result, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, limit *int32) ([]*model.SearchResult, error) {
	l := 10
	if limit != nil {
		l = int(*limit) // Konvertierung int32 -> int
	}

	// Request Objekt für den Searcher bauen
	req := domain.SearchRequest{
		Query:    query,
		Limit:    l,
		MinScore: 0.25,
	}

	hits, err := r.Searcher.Search(ctx, req)
	if err != nil {
		return nil, err
	}

	var result []*model.SearchResult
	for _, h := range hits {
		// Pointer Helper für String-Feld
		sig := h.Chunk.Signature

		result = append(result, &model.SearchResult{
			FilePath:  h.Chunk.FilePath,
			StartLine: int32(h.Chunk.StartLine),
			EndLine:   int32(h.Chunk.EndLine),
			Content:   h.Chunk.Content,
			Score:     h.CombinedScore,
			Signature: &sig,
		})
	}
	return result, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// Middleware Import muss vorhanden sein!
	userID, err := middleware.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, nil // Kein User eingeloggt
	}

	user, err := r.AuthService.Me(ctx, userID)
	if err != nil {
		return nil, err
	}
	return mapDomainUserToModel(user), nil
}

// LlmInfo is the resolver for the llmInfo field.
func (r *queryResolver) LlmInfo(ctx context.Context) (*model.LLMInfo, error) {
	// Einfacher Aufruf über das Interface!
	available, err := r.Embedder.ListModels(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch models: %w", err)
	}

	return &model.LLMInfo{
		CurrentModel:    r.Embedder.GetCurrentModel(),
		AvailableModels: available,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }


func unzipFile(r io.Reader, size int64, dest string) error {
	// graphql.Upload.File ist ein io.ReadSeeker, wir brauchen aber ReaderAt für zip.NewReader
	// Da File oft ein *os.File ist, können wir casten, oder wir lesen alles in den Speicher (weniger effizient).
	// Besser: Wir nutzen einen Adapter, wenn ReaderAt benötigt wird.

	// Da zip.NewReader ReaderAt benötigt, und graphql.Upload meistens eine temp Datei auf Disk ist:
	file, ok := r.(io.ReaderAt)
	if !ok {
		return fmt.Errorf("upload file interface does not support ReaderAt")
	}

	reader, err := zip.NewReader(file, size)
	if err != nil {
		return err
	}

	for _, f := range reader.File {
		fpath := filepath.Join(dest, f.Name)

		// Zip Slip Protection
		if !strings.HasPrefix(fpath, filepath.Clean(dest)+string(os.PathSeparator)) {
			return fmt.Errorf("illegal file path: %s", fpath)
		}

		if f.FileInfo().IsDir() {
			os.MkdirAll(fpath, os.ModePerm)
			continue
		}

		if err := os.MkdirAll(filepath.Dir(fpath), os.ModePerm); err != nil {
			return err
		}

		outFile, err := os.OpenFile(fpath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode())
		if err != nil {
			return err
		}

		rc, err := f.Open()
		if err != nil {
			outFile.Close()
			return err
		}

		_, err = io.Copy(outFile, rc)
		outFile.Close()
		rc.Close()
		if err != nil {
			return err
		}
	}
	return nil
}
func mapDomainRepoToModel(d *domain.Repository) *model.Repository {
	return &model.Repository{
		ID:          d.ID.String(),
		Name:        d.Name,
		Path:        d.Path,
		Status:      string(d.Status),
		LastIndexed: nil,
		FileCount:   int32(d.FileCount),
		ChunkCount:  int32(d.ChunkCount),
		ErrorMsg:    &d.ErrorMsg,
	}
}
func mapDomainUserToModel(u *domain.User) *model.User {
	return &model.User{
		ID:       u.ID.String(),
		Username: u.Username,
		Role:     string(u.Role),
	}
}
