// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type LLMInfo struct {
	CurrentModel    string   `json:"currentModel"`
	AvailableModels []string `json:"availableModels"`
}

type Mutation struct {
}

type Query struct {
}

type Repository struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Path        string     `json:"path"`
	Status      string     `json:"status"`
	LastIndexed *time.Time `json:"lastIndexed,omitempty"`
	FileCount   int32      `json:"fileCount"`
	ChunkCount  int32      `json:"chunkCount"`
	ErrorMsg    *string    `json:"errorMsg,omitempty"`
}

type SearchResult struct {
	FilePath  string  `json:"filePath"`
	StartLine int32   `json:"startLine"`
	EndLine   int32   `json:"endLine"`
	Content   string  `json:"content"`
	Score     float64 `json:"score"`
	Signature *string `json:"signature,omitempty"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Role     string `json:"role"`
}
